augment: true
augment_times: 1
augment_times_query: 1
backbone:
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
  name: Conv64F
batch_size: 16
classifier:
  kwargs: null
  name: ProtoNetCV
data_root: '~/'
deterministic: true
device_ids: 1
episode_size: 1
epoch: 100
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- backbones/Conv64F.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    T_max: 100
    eta_min: 0
  name: CosineAnnealingLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.001
    weight_decay: 0.0005
  name: Adam
  other: null
parallel_part:
- emb_func
pretrain_path: null
query_num: 15
result_root: '~/'
resume: false
save_interval: 10
save_part:
- emb_func
seed: 0
shot_num: 5
tag: null
tb_scale: 3.333333
test_episode: 600
test_epoch: 5
test_query: 15
test_shot: 5
test_way: 5
train_episode: 2000
use_memory: false
way_num: 20

eval_types: oracle
hpo: false
hpo_trials: 64
test: false
boot_rounds: 20
k_fold: 5