augment: true
# augment_method: AutoAugment
augment_times: 1
augment_times_query: 1
backbone:
  kwargs:
    is_feature: false
    is_flatten: true
    last_pool: true
    leaky_relu: false
    negative_slope: 0.2
  name: Conv64F
batch_size: 16
boot_rounds: 20
classifier:
  kwargs:
    feat_dim: 256
    inner_param:
      lr: 0.1
      test_iter: 10
      train_iter: 10
  name: MAML
data_root: '~/'
dataloader_num: 1
deterministic: true
device_ids: '3'
episode_size: 1
epoch: 100
eval_types: oracle,cross_val,bootstrapping
experimental: false
hpo: false
hpo_trials: 64
image_size: 32
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
k_fold: 5
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 20
  name: StepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.001
    momentum: 0.9
    weight_decay: 0.0005
  name: SGD
  other: null
parallel_part: emb_func
port: 53124
pretrain_path: null
query_num: 15
rank: 0
result_root: '~/'
resume: false
save_interval: 10
save_part: emb_func
seed: 42
shot_num: 5
tag: null
tb_scale: 3.3333333333333335
test_episode: 600
test_epoch: 5
test_query: 15
test_shot: 5
test_way: 5
train_episode: 2000
use_memory: false
val_per_epoch: 1
warmup: 0
way_num: 5
workers: 8
test: false