augment: true
augment_times: 1
augment_times_query: 1
backbone:
  kwargs:
    avg_pool: true
    is_feature: false
    is_flatten: true
    last_block_stride: 2
  name: resnet18
batch_size: 16
classifier:
  kwargs:
    feat_dim: 512
    inner_param:
      inner_batch_size: 4
      inner_optim:
        kwargs:
          dampening: 0.9
          lr: 0.01
          momentum: 0.9
          weight_decay: 0.001
        name: SGD
      inner_train_iter: 100
    num_class: 1149
  name: BaselinePlusCV
deterministic: true
device_ids: 3
episode_size: 1
epoch: 400
image_size: 128
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/Baseline++.yaml
log_interval: 100
log_level: info
log_name: null
log_paramerter: false
lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 100
  name: StepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.001
  name: Adam
  other: null
parallel_part:
- emb_func
port: 53193
pretrain_path: null
query_num: 15
rank: 0
result_root: '~/'
resume: false
save_interval: 50
save_part:
- emb_func
seed: 42
shot_num: 5
tag: null
tb_scale: 100.0
test_episode: 600
test_epoch: 5
test_query: 15
test_shot: 5
test_way: 5
train_episode: 2500
use_memory: false
way_num: 5
workers: 8

eval_types: oracle
# eval_types: oracle, cross_val
# eval_types: oracle
k_fold: 10
boot_rounds: 30
hpo: false
hpo_trials: 64
test: false


cross_domain: true
data_root: '~/'
train_datasets:
  - 44298/DOG_Mini
  - 44292/INS_2_Mini
  - 44293/PLT_NET_Mini
  - 44299/MED_LF_Mini
  - 44297/PNU_Mini
  - 44300/RSICB_Mini
  - 44295/APL_Mini
  - 44294/TEX_DTD_Mini
  - 44291/ACT_40_Mini
  - 44296/MD_5_BIS_Mini
val_datasets:
  - 44305/AWA_Mini
  - 44306/INS_Mini
  - 44302/FNG_Mini
  - 44303/PLT_DOC_Mini
  - 44308/PRT_Mini
  - 44307/RSD_Mini
  - 44309/BTS_Mini
  - 44304/TEX_ALOT_Mini
  - 44301/ACT_410_Mini
  - 44310/MD_6_Mini
test_datasets:
  - 44285/BRD_Mini
  - 44282/PLK_Mini
  - 44283/FLW_Mini
  - 44286/PLT_VIL_Mini
  - 44281/BCT_Mini
  - 44290/RESISC_Mini
  - 44289/CRS_Mini
  - 44288/TEX_Mini
  - 44284/SPT_Mini
  - 44287/MD_MIX_Mini