test_way: 10
test_shot: 5
test_query: 15
test_episode: 600

backbone: ViT-B/32
result_root: /raid/s2589574/Models/CLIP
data_root: /raid/s2589574/datasets/
test_datasets:
  - food-101

eval_types: oracle
boot_seed: 42
boot_rounds: 30
k_fold: 5