# log settings
log_name: ~ # if not ~: use for log file's name
log_level: info
log_interval: 100
log_paramerter: False # save the parameter as histogram or not

result_root: /afs/inf.ed.ac.uk/user/s25/s2589574/BEPE/Models
save_interval: 10
save_part:
  - emb_func

tag: ~
