includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml


batch_size: 16
# batch_size: 32
# few shot settings
# test way/shot are the same as train
augment: true
augment_times: 1
augment_times_query: 1
way_num: 5
shot_num: 5
query_num: 15
episode_size: 1
train_episode: 2000
# train_episode: 1000
# test_episode: 300
test_episode: 600
experimental: false
eval_types: oracle
# eval_types: oracle, cross_val
k_fold: 10
workers: 8
seed: 42
boot_rounds: 20
port: 53124

device_ids: 1
n_gpu: 1
epoch: 100

result_root: '~/'
data_root: '~/'

lr_scheduler:
  kwargs:
    gamma: 1.0
    step_size: 20
  name: StepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.01
    momentum: 0.9
    weight_decay: 0.0005
  name: SGD
  other: null

backbone:
  name: Conv64F
  kwargs:
    is_flatten: true
    is_feature: false
    leaky_relu: false
    negative_slope: 0.2
    last_pool: true

classifier:
  name: MAMLCV
  kwargs:
    inner_param:
      lr: 0.01
      train_iter: 10
      test_iter: 10
    feat_dim: 1600

hpo: false
hpo_trials: 15
test: false
image_size: 84
tb_scale: 3.33333